# Generated by Django 4.1.2 on 2022-10-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeshTermList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_url', models.CharField(max_length=200)),
                ('query_title', models.CharField(max_length=200)),
                ('query_abstract', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MeshTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meshterm_text', models.CharField(max_length=200)),
                ('meshterm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.meshtermlist')),
            ],
        ),
    ]
