# Generated by Django 4.1.2 on 2022-10-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_rename_meshterm_meshterm_meshterm_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meshtermlist',
            name='query_abstract',
        ),
        migrations.RemoveField(
            model_name='meshtermlist',
            name='query_title',
        ),
        migrations.AddField(
            model_name='meshtermlist',
            name='query_title_abstract',
            field=models.CharField(default=0, max_length=600),
            preserve_default=False,
        ),
    ]
